/**
 * ZKTeco PUSH protocol: "CmdID ... is generated by the server randomly,
 * supporting numbers and letters, with a length not over 16". Our queue ids
 * are UUIDs (36 characters with dashes), which strict terminals refuse, so no
 * name ever reached the screen and no command was ever acknowledged.
 *
 * deviceCommandId() maps a queue id to the id sent to the terminal:
 *  - ids that already fit (1-16 letters/digits) are sent as they are;
 *  - UUIDs become a decimal number of at most 16 digits, made from 13 random
 *    hex digits of the UUID (the version digit is skipped). It is stable, so
 *    the terminal's reply can be matched back without storing anything.
 */
const FITS_RE = /^[A-Za-z0-9]{1,16}$/;
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function deviceCommandId(queueId: string | number): string {
  const id = String(queueId);
  if (FITS_RE.test(id)) return id;
  if (UUID_RE.test(id)) {
    const hex = id.replace(/-/g, '').toLowerCase();
    return BigInt('0x' + hex.slice(0, 12) + hex.slice(13, 14)).toString(10); // < 2^52: max 16 digits
  }
  // Unknown id shape: fall back to a stable 16-digit number derived from it.
  let h = BigInt(0);
  for (const ch of id) h = (h * BigInt(131) + BigInt(ch.charCodeAt(0))) % BigInt('9007199254740881');
  return h.toString(10).slice(0, 16) || '0';
}

/** Is this what a terminal may legitimately echo back as a command id? */
export function isDeviceCommandId(value: string | null): value is string {
  return !!value && FITS_RE.test(value);
}
