export NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
export NEXT_PUBLIC_SUPABASE_ANON_KEY=lab-anon-key
export SUPABASE_SERVICE_ROLE_KEY=lab-service-key
export ZKTECO_DEVICE_SECRET=GLOBAL-shared-secret-123456
export NAJIKI_API_KEY=lab-najiki-secret
export NEXT_TELEMETRY_DISABLED=1
