import pg from 'pg';
import { execSync } from 'child_process';
import { setupUsers, sessionCookie, actionIds, callAction, SHIM } from './lib.mjs';
import seedMod from './seed.js';
const { IDS: { A } } = seedMod;
const [BASE, APPDIR] = process.argv.slice(2);
if (!process.env.SKIP_SEED) execSync('node seed.js'); await fetch(SHIM + '/__reload', { method: 'POST' }); await setupUsers();
const ck = await sessionCookie('adminA@lab.io'); const ids = actionIds(APPDIR);
const act = (n, args) => { const a = ids[n][0]; return callAction(BASE, '/' + a.page.replace(/^app\//,'').replace(/\/page$/,'').replace('[classId]', A.cls), a.id, args, ck); };
const fd = (o) => { const f = new FormData(); for (const [k, v] of Object.entries(o)) f.append(k, v); return f; };
let bad = 0;
const ok = (name, r, pred) => { const v = r.value; const pass = pred ? pred(v) : v && !v.error && v.success !== false; if (!pass) bad++; console.log((pass ? 'OK   ' : 'FAIL ') + name + '  ' + JSON.stringify(v).slice(0, 140)); };
ok('add student to own class', await act('addPersonAction', [fd({ fullName: 'New Kid', role: 'student', classId: A.cls, deviceUserId: '150', guardianName: 'Mum', guardianPhone: '+256700111222' })]));
ok('add teacher with own class', await act('addPersonAction', [fd({ fullName: 'New Teacher', role: 'teacher', phone: '+256700333444', classIdsJson: JSON.stringify([A.cls]) })]));
ok('add class with own teacher', await act('addClassAction', [fd({ name: 'P7 Blue', teacherId: A.teacher })]));
ok('record own teacher present', await act('recordTeacherAttendance', [A.teacher, 'present']));
ok('update own device id', await act('updatePersonDeviceUserIdAction', [A.student, '160']));
const pr = await act('resetTeacherPinAction', [A.teacher]); ok('reset own teacher PIN', pr); const NEWPIN = pr.value.newPin;
ok('push candidates own class', await act('getDevicePushCandidatesAction', [{ category: 'class', classId: A.cls, deviceSerialNumber: 'SNA0001' }]));
ok('push to own device', await act('pushUsersToDeviceAction', [{ deviceSerialNumber: 'SNA0001', category: 'all' }]));
ok('push to all own devices', await act('pushUsersToDeviceAction', [{ category: 'all' }]));
ok('auto-assign own device', await act('autoAssignDevicePinsAction', [{ deviceSerialNumber: 'sna0001', category: 'all' }]));
ok('push all own device', await act('pushAllUsersToDeviceAction', ['SNA0001']));
ok('regenerate own device secret', await act('regenerateDeviceSecretAction', [A.device]));
ok('add new device', await act('addDeviceAction', [fd({ serialNumber: 'sna0099', label: 'Back gate', deviceType: 'zkteco_adms' })]));
ok('own class roster', await act('getStudentsForClass', [A.cls]), (v) => JSON.stringify(v).includes('A-SECRETNAME'));
ok('kiosk clock-in own student', await act('submitClockInAction', ['160']));
ok('manual class attendance', await act('submitClassAttendance', [A.cls, A.teacher, [A.student], [], 'check_in', NEWPIN]));
ok('search own people', await act('searchPeopleAction', [{ searchTerm: 'Student', page: 1, limit: 50 }]), (v) => JSON.stringify(v).includes('A-SECRETNAME'));
const db = new pg.Client({ host: '127.0.0.1', port: 54329, user: 'postgres', password: 'pw', database: 'mtlab' }); await db.connect();
const cmds = (await db.query("SELECT count(*)::int n FROM school.device_commands WHERE school_id=$1", [A.school])).rows[0].n;
const n = (await db.query("SELECT count(*)::int n FROM school.notifications WHERE school_id=$1", [A.school])).rows[0].n;
console.log('A device_commands:', cmds, ' A notifications:', n); await db.end();
console.log(bad ? `${bad} FAILURES` : 'ALL LEGIT FLOWS OK');
